#!/bin/sh

# function
manual       () {
  "$@" --help | less
}   
run_as_root  () {
  su root -c "$(echo $@)"
}
play_media   () {
  ffplay -af atempo="$2" "$1" -vf setpts="1/$2*PTS" 
}
calculate () {
	awk "BEGIN { print $*}"
}


# alias
alias \
        g="git" \
	gcm="g add -u; g commit --amend -m $@" \
	dot="g --git-dir=$HOME/.dot --work-tree=$HOME" \
	dcm="dot add -u; dot commit --amend -m $@" \
        t="trizen" \
        h="manual" \
        e="nvim -n" \
        n="nix-env" \
        r="run_as_root" \
        p="r pacman $@" \
        pl="play_media" \
	cal="calculate" \
	ip4="curl -4 icanhazip.com"\
        sus="r 'printf mem > /sys/power/state'" \
        hib="r 'printf disk > /sys/power/state'" \
        ls="ls -hN --color=auto --group-directories-first" \
	ch="brave-browser --user-data-dir=/tmp & disown && exit" \
	bv="chromium --user-data-dir=/tmp & disown && exit" \
	up="r sh $HOME/.config/shell/scripts/backupgrade.sh" \
        vm="mkdir /tmp/mytpm1 & swtpm socket --tpmstate dir=/tmp/mytpm1 --ctrl type=unixio,path=/tmp/mytpm1/swtpm-sock --log level=20 --tpm2 & qemu-system-x86_64 -enable-kvm -boot menu=on -m 2g -cpu host -vga virtio -chardev socket,id=chrtpm,path=/tmp/mytpm1/swtpm-sock -tpmdev emulator,id=tpm0,chardev=chrtpm -device tpm-tis,tpmdev=tpm0" \
	# -bios /usr/share/ovmf/x64/OVMF.fd " \ 
        # -drive file=img,if=none,id=nvm -device nvme,serial=deadbeef,drive=nvm \
