#!/bin/sh

# function
manual       () {
  "$@" --help | less
}   
run_as_root  () {
  su root -c "$(echo $@)"
}
play_media   () {
  ffplay -af atempo="$2" "$1" -vf setpts="1/$2*PTS" 
}
calculate () {
	awk "BEGIN { print $*}"
}


# alias
alias \
        g="git" \
        t="trizen" \
        h="manual" \
        e="nvim -n" \
        n="nix-env" \
        r="run_as_root" \
        p="r pacman $@" \
        pl="play_media" \
	cal="calculate" \
        sus="r 'printf mem > /sys/power/state'" \
        hib="r 'printf disk > /sys/power/state'" \
	dot="git --git-dir=$HOME/.dot --work-tree=$HOME" \
        ls="ls -hN --color=auto --group-directories-first" \
	up="r sh $HOME/.config/shell/scripts/backupgrade.sh" \
        vm="mkdir /tmp/mytpm1 & swtpm socket --tpmstate dir=/tmp/mytpm1 --ctrl type=unixio,path=/tmp/mytpm1/swtpm-sock --log level=20 --tpm2 & qemu-system-x86_64 -enable-kvm -boot menu=on -m 2g -cpu host -vga virtio -chardev socket,id=chrtpm,path=/tmp/mytpm1/swtpm-sock -tpmdev emulator,id=tpm0,chardev=chrtpm -device tpm-tis,tpmdev=tpm0" \
	# -bios /usr/share/ovmf/x64/OVMF.fd " \ 
        # -drive file=img,if=none,id=nvm -device nvme,serial=deadbeef,drive=nvm \
