#!/bin/sh

# create required directory
mkdir  "$HOME/box"
rm -rf "$HOME/box/run"*

# set env variables
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CONFIG_HOME="$HOME/.config"
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export XDG_RUNTIME_DIR="$(mktemp -d $HOME/box/run.XXXXXXXXX)"
export WLR_NO_HARDWARE_CURSORS=1
export XDG_CACHE_HOME="$HOME/.cache"
export MOZ_ENABLE_WAYLAND=1
export WLR_LIBINPUT_NO_DEVICES=1
export MOZ_DBUS_REMOTE=1
export MOZ_USE_XINPUT2=1
export LANG="en_US.UTF-8"
export LC_ALL="C"
export EDITOR="nvim"
#export SOCKS_PROXY="socks5://127.0.0.1:9050"

# enable pipewire
 pipewire &
 pipewire-alsa &
 pipewire-pulse &
#pipewire-media-session &

# enable pulseaudio
 pulseaudio --kill
 pulseaudio --start -D

# launch graphical session
exec dbus-launch --sh-syntax --exit-with-session qtile start -b wayland  ||
exec dbus-launch --sh-syntax --exit-with-session qtile start  ||
sx sh "$HOME"/.config/x11/xinitrc ||
startx "$HOME"/.config/x11/xinitrc
