#!/bin/sh

# set env variables
# export XDG_RUNTIME_DIR="$(mktemp -d $HOME/box/run.XXXXXXXXX)"
export \
  XDG_DATA_HOME="$HOME/.local/share" \
  XDG_CONFIG_HOME="$HOME/.config" \
  XDG_CACHE_HOME="$HOME/.cache" \
  XDG_SESSION_TYPE=wayland \
  WLR_LIBINPUT_NO_DEVICES=1 \
  WLR_NO_HARDWARE_CURSORS=1 \
  PATH=$PATH:~/.local/bin:~/.nimble/bin \
  GDK_BACKEND=wayland,x11 \
  FLATPAK_ENABLE_SDK_EXT=* \
  EDITOR="e" \

#  MOZ_DISABLE_RDD_SANDBOX=1 \
#  MOZ_ENABLE_WAYLAND=1 \
#  MOZ_USE_XINPUT2=1 \
#  MOZ_DBUS_REMOTE=1 \
#  MOZ_LOG="PlatformDecoderModule:5" \
#  LANG="en_US.UTF-8" \
#  SOCKS_PROXY="socks5://127.0.0.1:9050" \

# Cosmic-Desktop
export \
  COSMIC_DATA_CONTROL_ENABLED=1 \
  XDG_CURRENT_DESKTOP=COSMIC \

# Set default Browser
xdg-settings set default-web-browser com.brave.Browser.desktop

# enable pipewire
#pipewire &
#pipewire-alsa &
pipewire-pulse &

# aria2 daemon
#aria2c --enable-rpc

# launch graphical session
# exec dbus-launch --sh-syntax --exit-with-session qtile start -b wayland \
dbus-run-session -- cosmic-session \
  || qtile start -b wayland \
  || sx sh "$HOME"/.config/x11/xinitrc \
  || startx "$HOME"/.config/x11/xinitrc
