theme = "fleet_dark"
# theme = "everblush"

[editor]
# line-number = "relative"
bufferline = "multiple"
cursorcolumn = true
cursorline = true
mouse = false
auto-format = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.statusline]
left = ["mode", "spinner", "version-control", "read-only-indicator", "file-modification-indicator"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.soft-wrap]
enable = true
max-wrap = 25 # increase value to reduce forced mid-word wrapping
max-indent-retain = 0


[editor.lsp]
display-inlay-hints = true

[editor.whitespace]
render = "all"

[editor.whitespace.characters]
nbsp = "⍽"
tab = "→"
tabpad = "·"
space = " " #"·"
newline = " " #"⏎"

[editor.indent-guides]
render = true
character = "╎" # "┆", "┊", "⸽"
skip-levels = 1

[keys.normal]
C-f = ["select_all", "select_regex"] # 'Ctrl f' to find
A-x = "extend_to_line_bounds"
X = ["extend_line_up", "extend_to_line_bounds"]

[keys.select]
A-x = "extend_to_line_bounds"
X = ["extend_line_up", "extend_to_line_bounds"]

[keys.insert.j]
k = "normal_mode" # `jk` to exit insert mode

[keys.normal."space"]
F = "file_picker_in_current_buffer_directory"
