[[language]]
name = "awk"
scope = "source.awk"
file-types = ["awk"]
language-servers = ["awk-language-server"]

[[language]]
name = "bash"
scope = "source.bash"
file-types = ["bash"]
language-servers = ["bash-language-server"]

[[language]]
name = "c"
scope = "source.c"
file-types = ["c"]
language-servers = ["clangd"]

[[language]]
name = "typescript"
scope = "source.ts"
file-types = ["ts"]
language-servers = ["typescript-language-server"]

[[language]]
name = "markdown"
scope = "source.markdown"
file-types = ["md"]
language-servers = ["marksman"]

[[language]]
name = "nim"
scope = "source.nim"
file-types = ["nim"]
language-servers = ["nimlangserver"]

[[language]]
name = "nix"
scope = "source.nix"
file-types = ["nix"]
language-servers = ["nil"]

[[language]]
name = "python"
scope = "source.python"
file-types = ["py"]
language-servers = ["pylsp"]

[[language]]
name = "rust"
scope = "source.rust"
file-types = ["rs"]
language-servers = ["rust-analyzer"]

[language-server.awk-language-server]
command = "awk-language-server"
args = ["--stdio"]

[language-server.bash-language-server]
command = "bash-language-server"
args = ["start"]

[language-server.clangd]
command = "clangd"
args = ["--background-index"]

[language-server.typescript-language-server]
command = "typescript-language-server"
args = ["--stdio"]

[language-server.marksman]
command = "marksman"
args = ["--stdio"]

[language-server.nimlangserver]
command = "nimlangserver"
args = ["--stdio"]

[language-server.nil]
command = "nil"
args = ["--stdio"]

[language-server.pylsp]
command = "pylsp"
args = ["--stdio"]

[language-server.rust-analyzer]
command = "rust-analyzer"
args = ["--stdio"]

[language-server.awk-language-server.config]
format = { command = "awk-language-server", args = ["--stdin"] }

[language-server.bash-language-server.config]
format = { command = "bash-language-server", args = ["--stdin"] }

[language-server.clangd.config]
format = { command = "clangd", args = ["--stdin"] }

[language-server.typescript-language-server.config]
format = { command = "typescript-language-server", args = ["--stdin"] }

[language-server.marksman.config]
format = { command = "marksman", args = ["--stdin"] }

[language-server.nimlangserver.config]
format = { command = "nimlangserver", args = ["--stdin"] }

[language-server.nil.config]
format = { command = "nil", args = ["--stdin"] }

[language-server.pylsp.config]
format = { command = "pylsp", args = ["--stdin"] }

[language-server.rust-analyzer.config]
format = { command = "rust-analyzer", args = ["--stdin"] }
